-- Create tag type enum
create type tag_type as enum (
  'vault',
  'blacklist',
  'bundle',
  'custom',
  'giveaway',
  'library',
  'steam_bundle',
  'steam_package',
  'tradelist',
  'wishlist'
);

-- Create tags table
create table tags (
  id integer generated by default as identity primary key,
  title text not null unique,
  type tag_type,
  updated_at timestamptz default null,
  created_at timestamptz default now()
);

-- Add table comment
comment on table tags is 'Tags for categorizing items in collections and vaults';

-- Add date management triggers
create trigger tags_update_dates
before update on tags
for each row
execute function update_dates();

create trigger tags_insert_dates
before insert on tags
for each row
execute function insert_dates();

-- Enable RLS
alter table tags enable row level security;

-- Allow read access for all users
create policy tags_select on tags
for select
to authenticated, anon
using (true);

-- Disallow creation for all users
-- Disallow updates for all users
-- Disallow deletions for all users