blank_issues_enabled: false
contact_links:
  - name: SteamKey.Trade Project Board
    url: https://github.com/users/Revadike/projects/5
    about: View our project board to see what we're currently working on
