name: Issue Report
description: Create a new issue for SteamKey.Trade
projects: ["Revadike/5"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!

        Please provide as much detail as possible to help us address your issue efficiently.

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Please provide a detailed description of the issue
      placeholder: Include steps to reproduce, expected behavior, and actual behavior if applicable
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      multiple: false
      options:
        - "Type: Bug"
        - "Type: Enhancement"
        - "Type: Feature"
        - "Type: Documentation"
        - "Type: Discussion"
        - "Type: Chore"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which part of the application is this issue related to?
      multiple: true
      options:
        - "Domain: Apps"
        - "Domain: Chat"
        - "Domain: Code"
        - "Domain: Collections"
        - "Domain: Layout"
        - "Domain: Matches"
        - "Domain: Notifications"
        - "Domain: Other"
        - "Domain: Reviews"
        - "Domain: Settings"
        - "Domain: Trades"
        - "Domain: Users"
        - "Domain: Vault"
    validations:
      required: true
