name: Issue Report
description: Create a new issue for SteamKey.Trade

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!

        Please provide as much detail as possible to help us address your issue efficiently.

  - type: input
    id: title
    attributes:
      label: Short title
      description: A short, clear summary of the issue
      placeholder: e.g. "Bundles feed"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Please provide a detailed description of the issue
      placeholder: Include steps to reproduce, expected behavior, and actual behavior if applicable
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What kind of issue is this?
      multiple: false
      options:
        - label: Bug
          value: "Type: Bug"
        - label: Enhancement
          value: "Type: Enhancement"
        - label: Feature
          value: "Type: Feature"
        - label: Documentation
          value: "Type: Documentation"
        - label: Discussion
          value: "Type: Discussion"
        - label: Chore
          value: "Type: Chore"
    validations:
      required: true

  - type: dropdown
    id: domain
    attributes:
      label: Domain
      description: Which part of the application is this issue related to?
      multiple: true
      options:
        - label: Apps
          value: "Domain: Apps"
        - label: Chat
          value: "Domain: Chat"
        - label: Code
          value: "Domain: Code"
        - label: Collections
          value: "Domain: Collections"
        - label: Layout
          value: "Domain: Layout"
        - label: Matches
          value: "Domain: Matches"
        - label: Notifications
          value: "Domain: Notifications"
        - label: Other
          value: "Domain: Other"
        - label: Reviews
          value: "Domain: Reviews"
        - label: Settings
          value: "Domain: Settings"
        - label: Trades
          value: "Domain: Trades"
        - label: Users
          value: "Domain: Users"
        - label: Vault
          value: "Domain: Vault"
    validations:
      required: true
